[project]
name = 'service-notifications'
version = '0.0.1'
description = 'Sending notifications has never been easier!'
dependencies = [
    'requests',
    'importlib-metadata; python_version<"3.10"',
]